"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-14 22:14:31.805892

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.String(length=128), nullable=True),
    sa.Column('on_behalf_of', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_operation_id'), 'audit_events', ['operation_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('internal_id', sa.String(length=64), nullable=False),
    sa.Column('git_locator', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('canonical_spec', sa.String(length=512), nullable=True),
    sa.Column('purpose', sa.String(length=256), nullable=True),
    sa.Column('owner_type', sa.String(length=8), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('internal_id'),
    sa.UniqueConstraint('bank_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id')
    )
    op.create_table('external_identities',
    sa.Column('issuer', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('credential_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('issuer', 'subject')
    )
    op.create_index(op.f('ix_external_identities_credential_id'), 'external_identities', ['credential_id'], unique=True)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('project_slugs',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('project_internal_id', sa.String(length=64), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_internal_id'], ['projects.internal_id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index('uq_project_slugs_canonical_project', 'project_slugs', ['project_internal_id'], unique=True, postgresql_where=sa.text('is_canonical'))
    op.create_table('working_states',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('workspace_id', sa.String(length=35), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_states')
    op.drop_index('uq_project_slugs_canonical_project', table_name='project_slugs', postgresql_where=sa.text('is_canonical'))
    op.drop_table('project_slugs')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_credential_id'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('groups')
    op.drop_index(op.f('ix_audit_events_operation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
